[Feature] listar usuários substitutos
codata-gedes/pbdoc pull request #206
Opened 2021-11-22 18:19 UTC by caiosantos-codata

Fix #154

2021-11-30 13:22 UTC, michelrisucci-codata requested changes
Não consegui fazer exibir os substitutos.
A paginação parece exibir dados, mas acredito que está exibindo um count com o algoritmo antigo.
Favor reavaliar e revalidar com quem registrou a issue.

cc @allyssoncruz @wendell-codata 

![image](https://user-images.githubusercontent.com/83982953/144055046-68684ab2-32e6-4e42-ba79-02d2758257b1.png)

2021-11-30 14:28 UTC, caiosantos-codata commented
@michelrisucci-codata ,

sobre os passos necessários para cadastrar/exibir substitutos, veja esse [comentário](https://github.com/codata-gedes/pbdoc/issues/154#issuecomment-975799077) na issue relacionada a esta PR. Qualquer coisa, pode comentar lá.

sobre a paginação, good catch.
faltou tratar essa consulta também. Irei revisá-la.

2021-11-30 14:51 UTC, michelrisucci-codata commented
> @michelrisucci-codata ,
> 
> sobre os passos necessários para cadastrar/exibir substitutos, veja esse [comentário](https://github.com/codata-gedes/pbdoc/issues/154#issuecomment-975799077) na issue relacionada a esta PR. Qualquer coisa, pode comentar lá.
> 
> sobre a paginação, good catch. faltou tratar essa consulta também. Irei revisá-la.

Beleza, @caiosantos-codata!

@allyssoncruz não tivemos resposta do comentário do @caiosantos-codata na issue #154. Poderia nos confirmar se é exatamente esse o ponto? Não achei a descrição da issue tão clara.

Por sinal, acredito que temos um problema nas descrições de algumas issues, @allyssoncruz! :warning: 
Considero que a informação precisa estar mais clara pra que possamos atuar. Algumas issues do cliente simplesmente não declaram o problema e deixam a cargo do desenvolvedor descobrir o que precisa ser feito.
Favor verificar se a descrição das issues está clara o suficiente pra entender o problema.
Se possível, **deixar uma descrição resumida sobre o que o mesmo deseja pra que fique mais claro**.

Resumindo de forma clara:
- favor confirmar se o que @caiosantos-codata solicitou é o cenário correto;
- lembrar de deixar mais claro as descrições das próximas atividades

2021-12-07 04:56 UTC, michelrisucci-codata approved these changes

2021-12-07 04:56 UTC, merged