Incluir coluna destino mesa virtual
codata-gedes/pbdoc pull request #246
Opened 2022-03-31 15:47 UTC by wendell-codata

2022-03-31 17:32 UTC, caiosantos-codata commented on siga-ex/src/main/java/br/gov/jfrj/siga/ex/bl/Mesa2.java
> +				try {
é preciso o `try-catch`? 
talvez verificar com `null` seja suficiente.

2022-03-31 17:32 UTC, caiosantos-codata commented on sigaex/src/main/webapp/WEB-INF/page/exMesa2/lista.jsp
> +											<th scope="col" class="col-1 d-none d-md-block">Tempo</th> aaa
o que seria esse 'aaa'?

2022-04-01 03:14 UTC, michelrisucci-codata commented on sigaex/src/main/webapp/WEB-INF/page/exMesa2/lista.jsp
> +											<th scope="col" class="col-1 d-none d-md-block">Tempo</th> aaa
@wendell-codata acho que isso foi um teste que foi errado. Corrige, por favor.
Boa, @caiosantos-codata

2022-04-01 03:19 UTC, michelrisucci-codata commented on siga-ex/src/main/java/br/gov/jfrj/siga/ex/bl/Mesa2.java
> +				try {
Concordo, @caiosantos-codata.

Wendell, em vez desse `if-else` todo aí, só colocar:
```java
			r.destino = Optional.ofNullable(mobil.doc())
					.map(ExDocumento::getLotaDestinatario)
					.map(DpLotacao::getSiglaLotacao)
					.orElse(null);
```

2022-04-01 03:21 UTC, michelrisucci-codata requested changes
@wendell-codata faz as correções que a gente pode mergear.

2022-04-01 15:15 UTC, wendell-codata commented on siga-ex/src/main/java/br/gov/jfrj/siga/ex/bl/Mesa2.java
> +				try {
blz... Vivendo e aprendendo.

2022-04-01 15:17 UTC, wendell-codata commented on sigaex/src/main/webapp/WEB-INF/page/exMesa2/lista.jsp
> +											<th scope="col" class="col-1 d-none d-md-block">Tempo</th> aaa
Senhores... esse 'aaa' era um marcado de linha pra que eu pudesse retornar.. estou eliminando

2022-04-05 00:25 UTC, michelrisucci-codata approved these changes

2022-04-05 00:25 UTC, merged