Troca botao cancelar voltar
codata-gedes/pbdoc pull request #260
Opened 2022-05-05 14:14 UTC by wendell-codata

Substituição do label do botão "Cancela" em muitos pontos do sistema pelo novo label "Voltar", conforme entendimento realizado em reunião.

2022-05-05 14:59 UTC, caiosantos-codata commented on siga-cp/src/main/resources/messages_SIGA.properties
> -botao.cancela=Cancela
acho que essa mudança pode gerar confusão.
O que acha de criar uma nova entrada `botao.voltar=Voltar` e utilizá-la ao invés de `botao.cancela`?

2022-05-05 15:00 UTC, caiosantos-codata commented on siga-cp/src/main/resources/messages_TRF2.properties
> -botao.cancela=Cancela
dúvida: utilizamos de fato esse arquivo de properties?

2022-05-05 15:01 UTC, caiosantos-codata commented on sigaex/src/main/webapp/WEB-INF/page/exMovimentacao/aAvaliar.jsp
> +							<input type="button" value="Voltar" onclick="javascript:history.back();" class="btn btn-cancel ml-2" />
aqui não caberia algo como:

```suggestion
<input type="button" value=<fmt:message key="botao.voltar"/> onclick="javascript:history.back();" class="btn btn-cancel ml-2" />
```
o que acha?

2022-05-05 16:45 UTC, michelrisucci-codata requested changes

2022-05-05 16:45 UTC, michelrisucci-codata commented on siga-cp/src/main/resources/messages_SIGA.properties
> -botao.cancela=Cancela
Concordo.
@wendell-codata a idéia é ter um ajuste pontual pras telas que precisamos mudar de CANCELAR para VOLTAR.
Fazer este tipo de alteração causa confusão.

2022-05-05 16:46 UTC, michelrisucci-codata commented on siga-cp/src/main/resources/messages_TRF2.properties
> -botao.cancela=Cancela
Não. Este é específico para o TRF.

2022-05-05 17:13 UTC, michelrisucci-codata commented on sigaex/src/main/webapp/WEB-INF/page/exMovimentacao/aAvaliar.jsp
> +							<input type="button" value="Voltar" onclick="javascript:history.back();" class="btn btn-cancel ml-2" />
Incrementei porque tava faltando as aspas no `<fmt value`.

2022-05-05 17:17 UTC, wendell-codata commented on siga-cp/src/main/resources/messages_SIGA.properties
> -botao.cancela=Cancela
Blz.... Acolhida a sugestão.

2022-05-05 17:26 UTC, michelrisucci-codata commented on siga-cp/src/main/resources/messages_SIGA.properties
> -botao.cancela=Cancela
Cria um `botao.voltar=Voltar` e referencia com `<fmt:message key="botao.voltar" />` nas telas, @wendell-codata.

2022-05-05 17:41 UTC, wendell-codata commented
Realizei a mudança de botao.cancelar=Cancela para botao.voltar=Voltar
Verifiquei que existem pontos em que a inserção está hard code. Estou alterando para todos utilizarem a partir do .properties. 
Aguardar conclusão.

2022-05-05 18:54 UTC, michelrisucci-codata commented on sigaex/src/main/resources/globalMessages.properties
> +botao.voltarr=Voltar
Tá errada a chave aqui, @wendell-codata. Outra coisa... A idéia é manter a chave `botao.cancelar` exatamente como tava antes

2022-05-05 18:59 UTC, michelrisucci-codata commented on sigaex/src/main/resources/globalMessages.properties
> +botao.voltarr=Voltar
Fazer isso pros outros arquivos também.

2022-05-09 04:05 UTC, michelrisucci-codata commented
@wendell-codata segunda-feira (10/05) envia tuas últimas modificações com as correções daqui pra a gente gerar versão, por favor.

2022-05-09 16:33 UTC, michelrisucci-codata approved these changes

2022-05-09 16:34 UTC, merged